--- 
abstract: A set of file tasks to be executed in a directory
author: 
  - Adam Kennedy <adamk@cpan.org>, L<http://ali.as/>
build_requires: 
  Class::Inspector: 1.11
  Test::ClassAPI: 1.02
  Test::More: 0.47
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: File-Tasks
no_index: 
  directory: 
    - inc
    - t
requires: 
  Archive::Builder: 1.04
  Clone: 0.21
  File::Find::Rule: 0.20
  File::Flat: 0.92
  File::Spec: 0.80
  List::Util: 1.15
  Params::Coerce: 0.05
  Params::Util: 0.06
  Scalar::Util: 1.15
  perl: 5.005
version: 0.07
