name: File-Tasks
version: 0.05
abstract: Manipulate sets of file tasks, to be applied to a filesystem
author: Adam Kennedy <adam@phase-n.com>
license: unknown
distribution_type: module
build_requires:
  Test::More: 0.47
  Test::ClassAPI: 1.02
requires:
  perl: 5.005
  Clone: 0.13
  File::Find::Rule: 0.20
  File::Flat: 0.92
  File::Spec: 0.82
  List::Util: 1.15
  Scalar::Util: 1.15
  Archive::Builder: 1.04
  Param::Coerce: 0.05
  Params::Util: 0.06
no_index:
  directory:
    - t.data
    - inc
generated_by: Module::Install version 0.37
